### ISSUE TITLE
test_results in reqtools_config.yml is a string and not an array

### ISSUE THREAD

**Issue by lfvjimisola** [luftfartsverket/reqstool-python-hatch-plugin#23]
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/reqstool_index.schema.json

# version: 0.4.2.dev17
language: python
build: hatch
resources:
  requirements: docs/reqstool/requirements.yml
  software_verification_cases: docs/reqstool/software_verification_cases.yml
  annotations: build/reqstool/annotations.yml
  test_results: "['build/junit.xml']"
```

should be

```yaml
  test_results: ['build/junit.xml']"
```
